turistikrota/kit.ui

- apps/docs/.storybook/preview.tsx
- apps/docs/src/stories/Introduction.mdx
> bug/content-loader: fix the issue

- .github/depandabot.yml
- README.md
- apps/docs/.eslintrc.cjs
- apps/docs/.storybook/main.ts
- apps/docs/.storybook/preview.tsx
- apps/docs/.storybook/turistikrota.theme.ts
- apps/docs/package.json
- apps/docs/postcss.config.cjs
- apps/docs/postcss.config.js
- apps/docs/src/stories/components/alert/Alert.mdx
- apps/docs/src/stories/components/alert/Alert.stories.tsx
- apps/docs/src/stories/components/alert/Alert.test.tsx
- apps/docs/src/stories/components/button/Button.mdx
- apps/docs/src/tailwind.css
- apps/docs/tailwind.config.cjs
- apps/docs/tailwind.config.js
- apps/docs/yarn.lock
- packages/ui/README.md
- packages/ui/package.json
- packages/ui/src/assets/config.css
> comp/alert: add documentation and tests for alert component

- apps/docs/package.json
- apps/docs/src/stories/components/accessibility/info/DesktopInfoBox.mdx
- apps/docs/src/stories/components/accessibility/info/DesktopInfoBox.stories.tsx
- apps/docs/src/stories/components/accessibility/info/DesktopInfoBox.test.tsx
- apps/docs/src/stories/components/accessibility/info/MobileInfoBox.mdx
- apps/docs/src/stories/components/accessibility/info/MobileInfoBox.stories.tsx
- apps/docs/src/stories/components/accessibility/info/MobileInfoBox.test.tsx
- apps/docs/src/stories/components/alert/Alert.stories.tsx
- apps/docs/yarn.lock
- packages/ui/package.json
- packages/ui/src/tooltip/index.tsx
comp/info-box: add mobile info box tests
*
---
*
Closes #12
> comp/info-box: add mobile info box stories

- apps/docs/src/app.tsx
- apps/docs/src/main.tsx
- apps/docs/src/stories/components/accessibility/info/DesktopInfoBox.stories.tsx
- apps/docs/src/stories/components/accessibility/info/MobileInfoBox.stories.tsx
- apps/docs/src/stories/components/alert/Alert.stories.tsx
- apps/docs/src/stories/components/button/Button.mdx
- apps/docs/src/stories/components/button/Button.stories.tsx
- apps/docs/src/stories/components/button/Button.test.tsx
> Comp/button: complete the button component tests and stories

- apps/docs/src/stories/utils/transform/Transform.mdx
- apps/docs/src/stories/utils/transform/Transform.stories.tsx
- apps/docs/src/stories/utils/transform/Transform.test.tsx
utils/transform: add tests
*
---
*
Closes #43
> utils/transform: add stories

- apps/docs/src/stories/utils/storage/Storage.mdx
- apps/docs/src/stories/utils/storage/Storage.stories.tsx
- apps/docs/src/stories/utils/storage/Storage.test.tsx
utils/storage: add tests
*
---
*
Closes #42
> utils/storage: add stories

- apps/docs/src/stories/utils/sort/Sort.mdx
- apps/docs/src/stories/utils/sort/Sort.stories.tsx
- apps/docs/src/stories/utils/sort/Sort.test.tsx
utils/sort: add tests
*
---
*
Closes #41
> utils/sort: add stories and tests

- apps/docs/src/stories/utils/async/Async.mdx
- apps/docs/src/stories/utils/async/Async.test.tsx
- apps/docs/src/stories/utils/debounce/Debounce.mdx
utils/async: add tests
*
---
*
Closes #38
> utils/async: add documentation

- apps/docs/package.json
- apps/docs/src/stories/utils/async/Async.test.tsx
- apps/docs/src/stories/utils/response/Response.mdx
- apps/docs/src/stories/utils/response/Response.test.tsx
- apps/docs/src/stories/utils/sort/Sort.mdx
- apps/docs/src/stories/utils/storage/Storage.mdx
- apps/docs/src/stories/utils/transform/Transform.mdx
- apps/docs/yarn.lock
- packages/ui/package.json
- packages/ui/src/utils/response.ts
utils: response add tests
*
---
*
Closes #40
> utils: response add documentation

- apps/docs/src/stories/components/alert/Alert.mdx
- apps/docs/src/stories/components/alert/Alert.stories.tsx
- apps/docs/src/stories/components/button/Button.mdx
- apps/docs/src/stories/components/button/Button.stories.tsx
- apps/docs/src/stories/components/username/Username.mdx
- apps/docs/src/stories/components/username/Username.stories.tsx
- apps/docs/src/stories/components/username/Username.test.tsx
comp/username: add stories
comp/username: add tests
*
---
*
Closes #37
> comp/username: add documentation

- apps/docs/src/stories/components/error-text/ErrorText.mdx
- apps/docs/src/stories/components/error-text/ErrorText.stories.tsx
- apps/docs/src/stories/components/error-text/ErrorText.test.tsx
comp/err-txt: add stories
comp/err-txt: add tests
*
---
*
Closes #34
> comp/err-txt: add documentation

- apps/docs/src/stories/components/content-loader/ContentLoader.mdx
- apps/docs/src/stories/components/content-loader/ContentLoader.stories.tsx
- apps/docs/src/stories/components/content-loader/ContentLoader.test.tsx
comp/content-loader: add stories
comp/content-loader: add tests
*
---
*
Closes #29
> comp/content-loader: add documentation

- apps/docs/src/stories/hooks/ssr/Ssr.mdx
> hooks/ssr: add documentation

- apps/docs/src/stories/hooks/dom/Dom.mdx
> hooks/dom: add documentation

- apps/docs/src/stories/components/condition/Condition.mdx
- apps/docs/src/stories/components/condition/Condition.stories.tsx
- apps/docs/src/stories/components/condition/Condition.test.tsx
comp/condition: add tests
comp/condition: add stories
*
---
*
Closes #15
> comp/condition: add documentation

- apps/docs/src/stories/components/tooltip/Tooltip.mdx
- apps/docs/src/stories/components/tooltip/Tooltip.stories.tsx
- apps/docs/src/stories/components/tooltip/Tooltip.test.tsx
comp/tooltip: add stories
comp/tooltip: add tests
*
---
*
Closes #36
> comp/tooltip: add documentation

- apps/docs/.storybook/preview.tsx
- apps/docs/.storybook/turistikrota.theme.ts
- apps/docs/src/stories/hooks/useToast/Toast.example.tsx
- apps/docs/src/stories/hooks/useToast/Toast.mdx
- apps/docs/src/stories/hooks/useToast/Toast.test.tsx
- apps/docs/src/tailwind.css
comp/toast: add tests
*
---
*
Closes #35
> comp/toast: add documentation

- apps/docs/.storybook/turistikrota.theme.ts
- apps/docs/src/stories/components/progress/Progress.mdx
- apps/docs/src/stories/components/progress/Progress.stories.tsx
- apps/docs/src/stories/components/progress/Progress.test.tsx
comp/progress: add stories
comp/progress: add tests
*
---
*
Closes #32
> comp/progress: add documentation

- apps/docs/src/stories/components/sections/disabled/DisabledSection.mdx
- apps/docs/src/stories/components/sections/disabled/DisabledSection.stories.tsx
- apps/docs/src/stories/components/sections/disabled/DisabledSection.test.tsx
- apps/docs/src/stories/components/tooltip/Tooltip.stories.tsx
comp/disabled: add stories
comp/disabled: add tests
*
---
*
Closes #33
> comp/disabled: add documentation

- apps/docs/src/stories/components/modal/Modal.mdx
- apps/docs/src/stories/components/modal/Modal.stories.tsx
- apps/docs/src/stories/components/modal/Modal.test.tsx
comp/modal: add stories
comp/modal: add tests
*
---
*
Closes #30
> comp/modal: add documentation

- apps/docs/src/stories/components/perfect-image/PerfectImage.mdx
- apps/docs/src/stories/components/perfect-image/PerfectImage.stories.tsx
- apps/docs/src/stories/components/perfect-image/PerfectImage.test.tsx
docs/perfect-img: add the stories
docs/perfect-img: add the tests
*
---
*
Closes #28
> docs/perfect-img: add the documentation

- apps/docs/src/stories/components/form/input/Input.mdx
- apps/docs/src/stories/components/form/input/Input.stories.tsx
- apps/docs/src/stories/components/form/input/Input.test.tsx
comp/input: add stories
comp/input: add tests
*
---
*
Closes #18
> comp/input: add documentation

- apps/docs/src/stories/components/form/line/Line.mdx
- apps/docs/src/stories/components/form/line/Line.stories.tsx
- apps/docs/src/stories/components/form/line/Line.test.tsx
comp/line-form: add stories
comp/line-form: add tests
*
---
*
Closes #19
> comp/line-form: add documentation

- apps/docs/src/stories/components/form/radio/Radio.mdx
- apps/docs/src/stories/components/form/radio/Radio.stories.tsx
- apps/docs/src/stories/components/form/radio/Radio.test.tsx
comp/radio: add stories
comp/radio: add tests
*
---
*
Closes #20
> comp/radio: add documentation

- apps/docs/src/stories/components/form/select/Select.mdx
- apps/docs/src/stories/components/form/select/Select.stories.tsx
- apps/docs/src/stories/components/form/select/Select.test.tsx
comp/select: add stories
comp/select: add tests
*
---
*
Closes #22
> comp/select: add documentation

- apps/docs/src/stories/components/form/section/Section.mdx
- apps/docs/src/stories/components/form/section/Section.stories.tsx
- apps/docs/src/stories/components/form/section/Section.test.tsx
comp/form-section: add stories
comp/form-section: add tests
*
---
*
Closes #23
> comp/form-section: add documentation

- apps/docs/src/stories/pages/error/ErrorPage.mdx
- packages/ui/src/pages/error.tsx
page/error: add error page story
*
---
*
`Closing #82`
> page/error: add error page

- apps/docs/src/stories/components/headers/MobileHeader.mdx
- apps/docs/src/stories/components/headers/TopHeader.mdx
- packages/ui/src/headers/mobile.tsx
- packages/ui/src/headers/top.tsx
comp/headers: add top header
*
---
*
Closing #80, #81
> comp/headers: add mobile header

- apps/docs/package-lock.json
- apps/docs/package.json
- apps/docs/src/stories/components/form/radio-group/RadioGroup.mdx
- apps/docs/src/stories/components/form/radio-group/RadioGroup.stories.tsx
- apps/docs/src/stories/components/form/select-group/SelectGroup.mdx
- apps/docs/src/stories/components/form/select-group/SelectGroup.stories.tsx
- packages/ui/package.json
- packages/ui/src/form/radio/group.tsx
- packages/ui/src/form/select/group.tsx
comp/radio-group: add select group component
comp/radio-group: add radio group docs
comp/radio-group: add select group docs
*
---
*
Closes #92
> comp/radio-group: add radio group component

- packages/ui/src/alert/index.tsx
> bug/alert-dark-mode: fix the issue

- apps/docs/package.json
- apps/docs/src/stories/utils/deep-equal/DeepEqual.mdx
- apps/docs/src/stories/utils/deep-equal/DeepEqual.test.tsx
- packages/ui/src/utils/index.ts
> utils/deep-equal: add the utility

- apps/docs/src/stories/utils/md/Markdown.mdx
- packages/ui/src/utils/md.ts
> utils/markdown: add utility

- apps/docs/src/stories/components/stars/Stars.mdx
- apps/docs/src/stories/components/stars/Stars.stories.tsx
- apps/docs/src/stories/components/stars/Stars.test.tsx
- packages/ui/src/stars/index.tsx
> component/stars: add the component

- apps/docs/src/stories/components/cards/feature/FeatureCard.mdx
- apps/docs/src/stories/components/cards/feature/FeatureCard.stories.tsx
- apps/docs/src/stories/components/cards/feature/FeatureCard.test.tsx
- packages/ui/src/cards/feature/core.tsx
- packages/ui/src/cards/feature/index.tsx
> component/feature-card: add the component

- apps/docs/package-lock.json
- apps/docs/src/stories/components/badge/Badge.mdx
- apps/docs/src/stories/components/badge/Badge.stories.tsx
- apps/docs/src/stories/components/badge/Badge.test.tsx
- packages/ui/package.json
- packages/ui/src/badge/index.tsx
- packages/ui/src/cards/feature/index.tsx
- packages/ui/src/types/index.ts
> component/badge: add the component

- apps/docs/src/stories/components/carousel/Carousel.stories.tsx
- apps/docs/src/stories/hooks/async/Async.mdx
- packages/ui/src/carousel/index.tsx
- packages/ui/src/hooks/async.tsx
> feature/carousel-next: update carousel component

- apps/docs/src/stories/components/sections/sticky/StickySection.mdx
- apps/docs/src/stories/components/sections/sticky/StickySection.stories.tsx
- apps/docs/src/stories/components/sections/sticky/StickySection.test.tsx
- packages/ui/src/headers/mobile.tsx
- packages/ui/src/hooks/header.tsx
- packages/ui/src/section/sticky/index.tsx
> feature/sticky-section: add the component

- apps/docs/package-lock.json
- apps/docs/package.json
- apps/docs/src/stories/components/image-preview/ImagePreview.mdx
- apps/docs/src/stories/hooks/dom/Dom.mdx
- apps/docs/src/stories/hooks/useToast/Toast.mdx
- apps/docs/src/utils/Summary.tsx
- apps/docs/tsconfig.json
- apps/docs/vite.config.ts
- packages/ui/package.json
- packages/ui/src/hooks/dom.tsx
docs: add summary component for native md details
*
---
*
> hook/infinite-scroll: add the scroll

- packages/ui/src/assets/tailwind.config.ts
- packages/ui/src/modal/index.tsx
- packages/ui/src/popup/index.tsx
> bug/modal-zindex: fix the issue

- apps/docs/package.json
- apps/docs/src/stories/hooks/dom/Dom.mdx
- apps/docs/src/stories/utils/deep-merge/DeepMerge.mdx
- apps/docs/src/stories/utils/deep-merge/DeepMerge.test.tsx
- packages/ui/package.json
- packages/ui/src/utils/index.ts
> util/deep-merge: add the util, test and docs

- apps/docs/package-lock.json
- apps/docs/package.json
- apps/docs/src/stories/utils/find-diff/FindDiff.mdx
- apps/docs/src/stories/utils/find-diff/FindDiff.test.tsx
- packages/ui/package.json
- packages/ui/src/utils/index.ts
> util/find-diff: add the findDiff utility

- packages/ui/package.json
- packages/ui/src/loader/index.tsx
> feature/design: add no margin option to content loader

- packages/ui/package.json
- packages/ui/src/image/perfect.tsx
> feature/design: add image loaded hook for perfect image

- packages/ui/package.json
- packages/ui/src/badge/index.tsx
> feature/design: add optional className props to badge

- packages/ui/package.json
- packages/ui/src/carousel/index.tsx
- packages/ui/src/image/perfect.tsx
> feature/image-loading: fix issue

- packages/ui/package.json
- packages/ui/src/timeline/index.tsx
> feature/timeline: add component

- packages/ui/package.json
- packages/ui/src/timeline/index.tsx
> feature/timeline: fix time item min-width

- packages/ui/package.json
- packages/ui/src/timeline/index.tsx
> feature/timeline: add system sub component

- packages/ui/package.json
- packages/ui/src/assets/tailwind.config.ts
- packages/ui/src/dropdown/index.tsx
> bugs/ui-colors: fix bug

- packages/ui/package.json
- packages/ui/src/assets/config.css
- packages/ui/src/assets/tailwind.config.ts
- packages/ui/src/headers/mobile.tsx
> bug/ui-colors: fix header color

- apps/docs/.storybook/preview-head.html
- apps/docs/index.html
> bug/meta-noindex: fix issue

- apps/docs/public/robots.txt
> bug/meta: add robots.txt
